name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main # или master, в зависимости от того, как называется ваша главная ветка

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Укажите версию Node.js, которую вы используете
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npx ng build --configuration production --base-href https://altach.github.io/ios-contact-app/

      # Фикс для роутинга Angular (чтобы при обновлении страницы на GitHub Pages не было ошибки 404)
      - name: Copy index.html to 404.html
        run: cp dist/contact-super-app/index.html dist/contact-super-app/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/contact-super-app'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
